from . import wizard_salary
from . import wizard_inss
from . import wizard_irt
from . import wizard_bank
from . import wizard_employee_extract
from . import wizard_contract_list
from . import hr_payroll_payslips_by_employees
from . import wizard_indication
from . import wizard_lote_payment
from . import wizard_template_irt
from . import wizard_absence_map
from . import wizard_bank_template