# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    "name": "Recursos Humanos  e Indicadores",
    "version": "18.0",
    "summary": "Gerir de forma eficiente o recursos humanos",
    "author": "Compllexus",
    "category": "Human Resources/Employees",
    "description": "Indicadores de recusos humanos",
    "sequence": -100,
    "website": "http://www.compllexus.com.",
    "depends": [
        "hr",
        "ao_localization",
        "hr_recruitment",
        "hr_timesheet",
        "hr_payroll",
        "l10n_ao_hr_payroll",
        "hr_holidays",
        "hr_attendance",
        "hr_work_entry_contract",
        "hr_appraisal",
        "hr_skills",
        "report_xlsx",
        # 'sign',
        # 'planning',
        # 'ao_hr_recruitment',
        # 'ao_hr_evaluation',
        # 'hr_contract_salary',
    ],
    "data": [
        "data/codes_deduction_data.xml",
        "data/codes_remuneration_data.xml",
        "data/contract_type.xml",
        # 'data/ir_sequence_data.xml',
        "data/mail_template.xml",
        "data/cron_data.xml",
        "data/contract_sequence.xml",
        # 'data/signature_template.xml',
        "security/security.xml",
        "menu/menu.xml",
        "views/res_company_view.xml",
        "views/parent_view.xml",
        "views/employee_view.xml",
        "views/contract_view.xml",
        # 'views/employee_appointment_sheet_view.xml',
        "views/remuneration_view.xml",
        "views/holidays_view.xml",
        "views/salaryrule_view.xml",
        "views/schedule_view.xml",
        "views/payslip_view.xml",
        "views/contract_proposal_view.xml",
        # 'views/absence_1.xml',
        # 'views/hr_appraisal_views.xml',
        # 'views/hr_appraisal_goal_views.xml',
        # 'views/leadership_development_plan_view.xml',
        # 'views/training_request_view.xml',
        "wizard/wizard_template_irt_view.xml",
        "wizard/wizard_salary_view.xml",
        "wizard/wizard_inss_view.xml",
        "wizard/wizard_irt_view.xml",
        "wizard/wizard_bank_view.xml",
        "wizard/wizard_employee_extract_view.xml",
        "wizard/wizard_contract_list_view.xml",
        "wizard/payroll_employee_wizard.xml",
        "wizard/wizard_indication.xml",
        "wizard/wizard_lote_payment_view.xml",
        "wizard/wizard_absence_map.xml",
        "wizard/wizard_bank_template_view.xml",
        "report/reports.xml",
        "report/report_bank.xml",
        "report/report_inss.xml",
        "report/report_irt.xml",
        "report/report_salary.xml",
        "report/report_simple_payslip.xml",
        # 'report/report_employee_file.xml',
        "report/report_employee_list.xml",
        "report/report_employee_list_department.xml",
        "report/report_work_declaration.xml",
        # 'report/report_evaluation_form_and_job_interview.xml',
        "report/report_irt_group_a.xml",
        "report/report_irt_group_bc.xml",
        "report/report_employee_extract.xml",
        "report/report_employee_contract_historic.xml",
        "report/report_leadership_development_plan.xml",
        "report/report_training_request.xml",
        "report/report_employee_contract_list.xml",
        "report/report_payslip.xml",
        "report/report_contract_determinado.xml",
        "report/indication.xml",
        "report/history_contract.xml",
        "report/report_contract_proposal.xml",
        "report/report_vacation_guide.xml",
        "report/report_absence_map.xml",
    ],
    "application": True,
    "auto_install": False,
    "installable": True,
    "price": 0.0,
    "license": "OPL-1",
    "currency": "AOA",
}
