from odoo import fields, models, api


class ModelName(models.Model):
    _name = 'absence.request.psi'
    _description = 'Pedido de ausencia'
    _inherit = ['mail.thread', 'mail.activity.mixin']

    department_boss = fields.Many2one('hr.employee', 'CD. Chefe de Departamento', tracking=True)
    employee_id = fields.Many2one('hr.employee', string='NOME', tracking=True)
    type_absence = fields.Many2one('hr.leave.type')
    qty_work_day = fields.Integer(default=22)
    other_details = fields.Text('Reason', tracking=True)
    day_lack = fields.Integer('Dia(s) Falta(s)')
    justified = fields.Boolean('Justificada', default=True)
    participation_training = fields.Many2one('hr.training.request')
    day_lack_1 = fields.Integer('Dia(s) Falta(s)')
    justified_2 = fields.Boolean('Justificada')
    participation_training_2 = fields.Char()
    comments = fields.Text()
    d1 = fields.Boolean('Jan')
    d2 = fields.Boolean('Fev')
    d3 = fields.Boolean('Mar')
    d4 = fields.Boolean('Abr')
    d5 = fields.Boolean("Maio")
    d6 = fields.Boolean('Jun')
    d7 = fields.Boolean('Jul')
    d8 = fields.Boolean('Ago')
    d9 = fields.Boolean('Set')
    d10 = fields.Boolean('Out')
    d11 = fields.Boolean('Nov')
    d12 = fields.Boolean('Dez')

    b16 = fields.Boolean('16')
    b17 = fields.Boolean('17')
    b18 = fields.Boolean('18')
    b19 = fields.Boolean('19')
    b20 = fields.Boolean('20')
    b21 = fields.Boolean('21')
    b22 = fields.Boolean('22')
    b23 = fields.Boolean('23')
    b24 = fields.Boolean('24')
    b25 = fields.Boolean('25')
    b26 = fields.Boolean('26')
    b27 = fields.Boolean('27')
    b28 = fields.Boolean('28')
    b29 = fields.Boolean('29')
    b30 = fields.Boolean('30')
    b31 = fields.Boolean('31')
    b1 = fields.Boolean('1')
    b2 = fields.Boolean('2')
    b3 = fields.Boolean('3')
    b4 = fields.Boolean('4')
    b5 = fields.Boolean('5')
    b6 = fields.Boolean('6')
    b7 = fields.Boolean('7')
    b8 = fields.Boolean('8')
    b9 = fields.Boolean('9')
    b10 = fields.Boolean('10')
    b11 = fields.Boolean('11')
    b12 = fields.Boolean('12')
    b13 = fields.Boolean('13')
    b14 = fields.Boolean('14')
    b15 = fields.Boolean('15')

    c1 = fields.Boolean('7,30')
    c2 = fields.Boolean('8,30')
    c3 = fields.Boolean('9.30')
    c4 = fields.Boolean('10,3')
    c5 = fields.Boolean('11,3')
    c6 = fields.Boolean('Intervalo        (12:30)')
    c7 = fields.Boolean('13,3')
    c8 = fields.Boolean('14,3')
    c9 = fields.Boolean('15,0')
    c10 = fields.Boolean('15,30')
    c11 = fields.Boolean('16,30')

    support = fields.Boolean('Document support')
    authorized = fields.Boolean('authorized por CD')
    holiday_swing = fields.Integer('holiday swing')

    number_low_medical = fields.Integer('No. of low medical')
